### ISSUE TITLE
Missing dependency on "requests" module

### ISSUE THREAD

**Issue by stephenatwork** [PlayFab/PythonSdk#8]
Repro on a clean machine:

py -m pip install playfab
py -e "import playfab"
ModuleNotFoundError: No module named 'requests'

**Comment by MGudgin** [comment]
Thanks for reporting this issue. I've submitted a PR to address it. Sorry it has taken us so long to get to this.

**Comment by MGudgin** [comment]
This was fixed with the 2020-03-30 [commit](https://github.com/PlayFab/PythonSdk/commit/6d1f04f6585cda6db3fa221dacd266e72de1bae4). 

Closing this issue.
