### ISSUE TITLE
invalid PlayFabErrorCode.Unknown in PlayFabHTTP.py#L75

### ISSUE THREAD

**Issue by hebre** [PlayFab/PythonSdk#9]
https://github.com/PlayFab/PythonSdk/blob/d2f5423dbd6a803cbe257c294b59657c5d8bf840/playfab/PlayFabHTTP.py#L75

now:
emptyResponseError.ErrorCode = PlayFabErrorCode.Unknown;
should be:
emptyResponseError.ErrorCode = PlayFabErrors.PlayFabErrorCode.Unknown;

**Comment by MGudgin** [comment]
Closing this issue now the fix is merged. Thanks again for reporting the problem.
